CREATE TABLE Users (
ID int NOT NULL AUTO_INCREMENT Primary key,
Login CHAR(25) NOT NULL,
Pass VARCHAR(128) NOT NULL);

CREATE TABLE Tasks (
ID int NOT NULL AUTO_INCREMENT Primary key,
Username CHAR (50) NOT NULL,
Email VARCHAR (100) NOT NULL,
Text VARCHAR (2000) NOT NULL,
ImageLink VARCHAR (100) NULL,
Status BIT,
CreateDate TIMESTAMP NULL);